---
- name: adding DNS record
  # hosts: 10.25.204.50
  tasks:
    - win_shell: "dnscmd  . /recordadd {{ dns_dev_zone_fwd }} {{ vm_name }} A {{ ip }}"
      # retries: 3
      # delay: 3
      # register: result
      # until: ("DNS_ERROR_RECORD_ALREADY_EXISTS" in result.stdout) or (result.rc == 0)
      #  failed_when: >
      #    ("DNS_ERROR_RECORD_ALREADY_EXISTS" not in result.stdout) and
      #    (result.rc != 0)
- name: IP Sections
  tasks:
    - ansible.builtin.set_fact:
        ip_sections: "{{ ip.split('.') | list }}"


- name: DEV zone PTR
  tasks:
    - ansible.builtin.set_fact:
        dns_dev_zone_ptr: "{{ ip_sections[2] }}.{{ ip_sections[1] }}.{{ ip_sections[0] }}.in-addr.arpa"

- name: Create REverse DNS records
  # hosts: 10.25.204.50
    - win_shell: "dnscmd . /RecordAdd {{ dns_dev_zone_ptr }} {{ ip_sections[3] }} PTR {{ vm_name }}"
  # retries: 3
  # delay: 3
  # register: result
  # until: ("DNS_ERROR_RECORD_ALREADY_EXISTS" in result.stdout) or (result.rc == 0)
  # failed_when: >
  # ("DNS_ERROR_RECORD_ALREADY_EXISTS" not in result.stdout) and
  # (result.rc != 0)
