---
- hosts: 192.168.80.5
  tasks:
    - name: adding DNS record
      win_shell: "dnscmd  . /recordadd {{ dns_dev_zone_fwd }} {{ vm_name }} A {{ ip }}"
      retries: 3
      delay: 3
      register: result
      until: ("DNS_ERROR_RECORD_ALREADY_EXISTS" in result.stdout) or (result.rc == 0)
      failed_when: >
        ("DNS_ERROR_RECORD_ALREADY_EXISTS" not in result.stdout) and
        (result.rc != 0)

    - name: Splitting ip and reversing order
      ansible.builtin.set_fact: 
        ip_sections: "{{ ip.split('.') | list }}"
        # dns_dev_zone_ptr: "{{ ip_sections[2] }}.{{ ip_sections[1] }}.{{ ip_sections[0] }}.in-addr.arpa"
        # reverse_lookup_ip: "{{ ip_sections[0] }}.{{ ip_sections[1] }}.{{ ip_sections[2] }}"

    - name: Create Reverse lookup zone
      become: true
      ansible.windows.win_powershell: 
         script: | 
           Add-DnsServerPrimaryZone -NetworkID "{{ reverse_lookup_ip }}.0/24" -ZoneFile "{{ dns_dev_zone_ptr }}.dns"

    - name: Create REverse DNS records
      win_shell: "dnscmd . /recordadd {{ dns_dev_zone_ptr }} {{ ip_sections[3] }} PTR {{ vm_name }}"
      retries: 3
      delay: 3
      register: result
      until: ("DNS_ERROR_RECORD_ALREADY_EXISTS" in result.stdout) or (result.rc == 0)
      failed_when: >
        ("DNS_ERROR_RECORD_ALREADY_EXISTS" not in result.stdout) and
        (result.rc != 0)