---
- hosts: 192.168.80.5
  tasks:
    - name: adding DNS record
      win_shell: "dnscmd  . /recordadd {{ dns_dev_zone_fwd }} {{ vm_name }} A {{ ip }}"

    - name: IP Sections
      ansible.builtin.set_fact:
        ip_sections: "{{ ip.split('.') | list }}"

    - name: DEV zone PTR
      ansible.builtin.set_fact:
        dns_dev_zone_ptr: "{{ ip_sections[2] }}.{{ ip_sections[1] }}.{{ ip_sections[0] }}.in-addr.arpa"
    
    - name: Reverse Zone dns file
      ansible.builtin.set_fact:
        reverse_lookup_ip: "{{ ip_sections[0] }}.{{ ip_sections[1] }}.{{ ip_sections[2] }}"

    - name: Create Reverse lookup zone
      become: true
      ansible.windows.win_powershell: 
         script: | 
           Add-DnsServerPrimaryZone -NetworkID "{{ reverse_lookup_ip }}.0/24" -ZoneFile "{{ dns_dev_zone_ptr }}.dns"

    # - name: Create REverse DNS records
    #   win_shell: "dnscmd . /recordadd {{ dns_dev_zone_ptr }} {{ ip_sections[3] }} PTR {{ vm_name }}"