---
- name: adding DNS record
  tasks:
    - win_shell: "dnscmd  . /recordadd {{ dns_dev_zone_fwd }} {{ vm_name }} A {{ ip }}"

- name: IP Sections
  tasks:
    - ansible.builtin.set_fact:
        ip_sections: "{{ ip.split('.') | list }}"


- name: DEV zone PTR
  tasks:
    - ansible.builtin.set_fact:
        dns_dev_zone_ptr: "{{ ip_sections[2] }}.{{ ip_sections[1] }}.{{ ip_sections[0] }}.in-addr.arpa"

- name: Create REverse DNS records
  tasks:
    - win_shell: "dnscmd . /RecordAdd {{ dns_dev_zone_ptr }} {{ ip_sections[3] }} PTR {{ vm_name }}"