---
- hosts: all
  become: true

  vars:
    ntp_server1: 0.asia.pool.ntp.org
    ntp_server2: 1.asia.pool.ntp.org
    ntp_server3: 2.asia.pool.ntp.org
    ntp_server4: 3.asia.pool.ntp.org

  tasks:
    - name: Check/install ntp client package
      package: name={{ item }} state=present update_cache=yes
      with_items:
        - ntp
        - git

    # - name: copying ntp file
    #   command: rm -R /etc/ntp_conf/

    # - name: cloning git repo
    #   ansible.builtin.git: 
    #     repo: https://github.com/EASILVANIA/TEST1.git
    #     dest: /etc/ntp_conf/

    # - name: copying ntp file
    #   command: cp /etc/ntp_conf/ntp.j2 /etc/ntp.conf
    #   ignore_errors: true

    - name: deploy ntp.conf to hosts
      ansible.builtin.template:
        remote_src: /etc/ntp_conf/ntp.j2
        dest: /etc/ntp.conf
        owner: root
        group: root
        mode: 0644
        backup: yes

    - name: ensure ntpd is running and enabled
      service:
        name=ntpd
        state=restarted
        enabled=yes