---
- hosts: all
  become: true

  vars:
    ntp_server1: 0.asia.pool.ntp.org
    ntp_server2: 1.asia.pool.ntp.org
    ntp_server3: 2.asia.pool.ntp.org
    ntp_server4: 3.asia.pool.ntp.org

  tasks:
    - name: Check/install ntp client package
      yum:
        update_cache=yes
        name=ntp
        state=present

    - name: deploy ntp.conf to hosts
      git:
        src=https://github.com/EASILVANIA/TEST1.git/ntp.j2
        dest=/etc/ntp.conf
        owner=root
        group=root
        mode=0644
        backup=yes

    - name: ensure ntpd is running and enabled
      service:
        name=ntpd
        state=restarted
        enabled=yes