---
- hosts: all
  become: true

  vars:
    ntp_server1: 0.asia.pool.ntp.org
    ntp_server2: 1.asia.pool.ntp.org
    ntp_server3: 2.asia.pool.ntp.org
    ntp_server4: 3.asia.pool.ntp.org

  tasks:
    - name: Check/install ntp client package
      package:
        name=ntp
        state=present

    - name: deploy ntp.conf to hosts
      git:
        repo=https://github.com/EASILVANIA/TEST1/blob/0c081d6a23c92afa331ef2383e6eb30ae4bfea9f/ntp.j2
        dest=/etc/ntp.conf

    - name: ensure ntpd is running and enabled
      service:
        name=ntpd
        state=restarted
        enabled=yes