---
 - hosts: "{{ ip }}"
   tasks:
     - name: checking if NTP is already running
       win_shell: w32tm /query /source
       register: NTP_config
	   
	   - name: checking NTP Peer
       win_shell: w32tm /query /peers
       register: NTP_peers
	   
	   - name: displaying config
       ansible.builtin.debug:
        var: 'NTP_config'
		 
	   - name: displaying Peer
       ansible.builtin.debug:
         var: 'NTP_peers'